# Generated by Django 2.2.4 on 2019-09-30 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
