# Generated by Django 2.2.4 on 2019-09-30 17:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rhymesapp', '0001_initial'),
    ]
